# Generated by Django 5.0.2 on 2024-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency", name="date", field=models.DateField(unique=True),
        ),
    ]
