# Generated by Django 5.0.2 on 2024-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currencyaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('monthly_buying', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('monthly_selling', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('quarterly_buying', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('quarterly_selling', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('annual_buying', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('annual_selling', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='currency',
            name='buying',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='currency',
            name='selling',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='currencyaverage',
            name='buying',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='currencyaverage',
            name='selling',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
    ]
