# Generated by Django 5.0.2 on 2024-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mizan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=100)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_currency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TL", "TL"),
                            ("USD", "USD"),
                            ("EURO", "EURO"),
                            ("STR", "STR"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "debit_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "credit_balance",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "total_balance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
