# Generated by Django 5.0.2 on 2024-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mizan",
            name="account_currency_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
