# Generated by Django 5.0.2 on 2024-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0002_alter_mizan_account_currency_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mizan",
            name="credit",
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="credit_balance",
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="debit",
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="debit_balance",
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="total_balance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
