# Generated by Django 5.0.2 on 2024-02-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0004_alter_mizan_debit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mizan",
            name="credit",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="credit_balance",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="debit_balance",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="total_balance",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
