# Generated by Django 5.0.2 on 2024-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0006_alter_mizan_credit_alter_mizan_credit_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mizan",
            name="credit",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="credit_balance",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="debit",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="debit_balance",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="mizan",
            name="total_balance",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
    ]
