# Generated by Django 5.0.2 on 2024-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_mizan_credit_alter_mizan_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mizan',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
