# Generated by Django 5.0.2 on 2024-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0008_alter_mizan_credit_alter_mizan_credit_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=100)),
                (
                    "converter_type",
                    models.CharField(
                        choices=[
                            ("average", "average"),
                            ("last", "last"),
                            ("instant", "instant"),
                            ("custom", "custom"),
                            ("none", "none"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
