# Generated by Django 5.0.2 on 2024-03-08 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0009_financialtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="mizan",
            name="date",
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 0, 0)),
            preserve_default=False,
        ),
    ]
