# Generated by Django 5.0.2 on 2024-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_mizan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MizanByDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_balance_january', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_february', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_march', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_april', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_may', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_june', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_july', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_august', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_september', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_october', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_november', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
                ('total_balance_december', models.DecimalField(decimal_places=15, default=0, max_digits=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
