# Generated by Django 5.0.2 on 2024-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_mizanbydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mizan',
            name='credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='credit_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='debit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='debit_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='total_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_april',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_august',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_december',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_february',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_january',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_july',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_june',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_march',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_may',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_november',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_october',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='mizanbydate',
            name='total_balance_september',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=40),
        ),
    ]
